package stowplex.lambda.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import stowplex.lambda.dao.customertype.CustomerType;
import stowplex.lambda.dao.customertype.CustomerTypeJSONMarshaller;
import stowplex.lambda.dao.login.Login;
import stowplex.lambda.dao.login.LoginJSONMarshaller;

import java.util.Set;

/**
 * Created by jcchn on 3/2/17.
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = CustomerInfoDAO.TABLE_NAME)
public class CustomerInfoDAO {
    public static final String TABLE_NAME = "CustomerInfo";

    private String cid;
    private Set<Login> logins;
    private CustomerType customerType;
    //TODO: DP?

    @JsonProperty
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getCid() {
        return cid;
    }

    public void setCid(String id) {
        this.cid = id;
    }

    @JsonProperty
    @DynamoDBAttribute
    @DynamoDBMarshalling(marshallerClass = LoginJSONMarshaller.class)
    public Set<Login> getLogins() {
        return logins;
    }

    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }

    @JsonProperty
    @DynamoDBAttribute
    @DynamoDBMarshalling(marshallerClass = CustomerTypeJSONMarshaller.class)
    public CustomerType getCustomerType() {
        return customerType;
    }

    public void setCustomerType(CustomerType customerType) {
        this.customerType = customerType;
    }
}
