package stowplex.lambda.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;

/**
 * Created by jcchn on 3/2/17.
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = stowplex.lambda.dao.FacebookProfileDAO.TABLE_NAME)
public class FacebookProfileDAO {
    public static final String TABLE_NAME = "FacebookProfile";

    private String id;
    private String cID;
    private String email;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getCID() {
        return cID;
    }

    public void setCID(String cid) {
        this.cID = cid;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
